/* eslint-disable max-lines */

import { TimeLineItemType } from "@/lib/types/Timeline"

export const timelineElements: TimeLineItemType[] = [
  {
    id: 9,
    title: "Infrastructure Engineer",
    description:
      "Setup of a complete enterprise infrastructure from scratch on Proxmox",
    company: "Proxmox Infra",
    startDate: new Date("sep 2025"),
    endDate: new Date("dec 2025"),
    category: "project",
    technologies: [
      "Proxmox",
      "OPNsense",
      "Nginx",
      "Keepalived",
      "Bind9",
      "Active Directory",
      "Zabbix",
      "Astro",
      "PostgreSQL",
    ],
    tasks: [
      "Firewall configuration on OPNsense",
      "DNS server setup with Bind9",
      "Active Directory implementation",
      "High-availability showcase website on 2 nodes (web1, web2, db-pg1, db-pg2) using Nginx, Keepalived, and PostgreSQL",
      "Zabbix monitoring server deployment",
      "Reverse proxy configuration",
      "Internal ticketing and wiki server",
      "Network isolation with separate VLANs",
    ],
    siteUrl: "",
    image: "projects/proxmox-infra.png",
  },
  {
    id: 8,
    title: "Fullstack Developer",
    description: "Subscription-based fitness social platform",
    company: "OnlyFits",
    startDate: new Date("jul 2025"),
    endDate: new Date("aug 2025"),
    category: "project",
    technologies: [
      "NextJs",
      "Better Auth",
      "TypeScript",
      "Stripe",
      "Tailwind",
      "MongoDB",
    ],
    tasks: [
      "User authentication & role management",
      "Content creation & subscription system",
      "Real-time chat & social features",
      "Stripe payment integration",
      "Multi-language support (FR/EN)",
      "Responsive UI with shadcn/ui",
      "MongoDB database design",
      "API development & state management",
    ],
    siteUrl: "",
    image: "projects/onlyfits.png",
  },
  {
    id: 7,
    title: "Apprenticeship as a Fullstack Developer",
    startDate: new Date("oct 2021"),
    endDate: new Date("30 sept 2024"),
    description: "Internal procedures automation",
    tasks: [
      "Requirements gathering and analysis to understand the business needs\n\r",
      "Create, build and maintain 11 internal applications to automate processes and improve operational efficiency\n\r",
      "Organized and led presentation meetings \n\r",
      "Agile development methodology",
    ],
    company: "HORIBA France",
    category: "work",
    technologies: [
      "NextJs",
      "Power Apps",
      "Power Automate",
      "SharePoint",
      "AgilePoint",
    ],
  },
  {
    id: 6,
    title: "Masters's Degree in Computer Science",
    startDate: new Date("sept 2022"),
    endDate: new Date("sept 2024"),
    description:
      "Obtained my Master's degree in computer science, where I learned the basics of programming.",
    company: "Sup De Vinci",
    category: "school",
    technologies: ["JavaScript"],
  },
  {
    id: 5,
    title: "Lead Developer",
    description:
      "Web application aimed at the professional retraining of military personnel",
    company: "Implic-Action",
    tasks: [
      "Manage a 7-man team, project planning",
      "Project architecture (structure, package selection, ESLint configuration, etc.)",
      "Break down complex epics into smaller, manageable tasks",
      "Full-stack development",
    ],
    startDate: new Date("aug 2024"),
    endDate: new Date("may 2024"),
    category: "project",
    technologies: [
      "NextJs",
      "Prisma",
      "Linear",
      "Github Actions",
      "Docker",
      "Tailwind",
      "Tanstack Query",
      "TypeScript",
    ],
    image: "projects/implic_action_onb_1.png",
  },
  {
    id: 4,
    title: "Fullstack Developer",
    description: "Tournament Management System Backend",
    company: "",
    startDate: new Date("feb 2024"),
    endDate: new Date("jan 2024"),
    category: "project",
    technologies: ["Go", "Cobra", "GORM", "SQLite", "JWT", "Viper"],
    tasks: [
      "Designed and implemented tournament management system architecture",
      "Created CLI interface using Cobra framework for tournament operations",
      "Implemented public and protected routes for API endpoints",
      "Used Viper for configuration management",
      "Implemented user authentication with JWT tokens and password hashing",
      "Developed CRUD operations for tournaments, teams, and matches",
      "Created interactive command-line prompts for user input",
      "Set up SQLite database with GORM ORM",
      "Implemented match scoring and winner determination logic",
    ],
    gitUrl: "https://github.com/matheusnb99/sdv-m2-renf-backend-go-cobra",
    image: "projects/golang.png",
  },

  {
    id: 3,
    title: "Fullstack Developer",
    description: "Azure Cloud VM Management Platform",
    company: "",
    startDate: new Date("jul 2023"),
    endDate: new Date("jul 2023"),
    category: "project",
    technologies: [
      "NextJs",
      "TypeScript",
      "Tailwind",
      "Prisma",
      "Azure",
      "Tanstack Query",
    ],
    tasks: [
      "Built cloud VM management platform using Azure",
      "Implemented 3-tier user authentication system",
      "Created automated VM lifecycle management",
      "Built RESTful API for Azure resources",
      "Added real-time VM monitoring",
      "Designed resource creation wizard",
      "Integrated Azure ARM APIs",
      "Implemented cost management",
      "Built responsive Tailwind UI",
    ],
    gitUrl: "https://github.com/matheusnb99/sdv-m1-cloud-azure-sky-spawner",
    image: "/projects/cloud.png",
  },

  {
    id: 2,
    title: "Fullstack Developer",
    description: "Japanese products e-commerce website",
    company: "Momotaro",
    startDate: new Date("jul 2023"),
    endDate: new Date("dec 2023"),
    category: "project",
    technologies: ["NextJs", "Next Auth", "TypeScript", "Express", "Tailwind"],
    siteUrl: "",
    image: "projects/momotaro.png",
    tasks: [
      "Developed a full-featured e-commerce platform for Japanese products",
      "Implemented user authentication and authorization with Next Auth",
      "Designed and built responsive UI using Tailwind CSS",
      "Integrated product catalog and shopping cart functionality",
      "Created secure checkout and order management system",
      "Built RESTful APIs with Express for backend operations",
      "Implemented product search and filtering features",
      "Set up admin dashboard for product and order management",
      "Optimized site performance and SEO for better user experience",
    ],
  },
  {
    id: 1,
    title: "Bachelor's Degree in Computer Science",
    startDate: new Date("sept 2021"),
    endDate: new Date("sept 2022"),
    description:
      "Obtained my Bachelor's degree in computer science, where I learned the basics of programming.",
    company: "Sup De Vinci",
    category: "school",
    technologies: [
      "JavaScript",
      "TypeScript",
      "React",
      "NextJs",
      "Spring Boot",
    ],
  },
  {
    id: 0,
    title: "DUT Informatique (Two-year technical degree in computer science)",
    description:
      "First year of my DUT in computer science, where I learned the basics of programming.",
    company: "Paris Saclay University",
    startDate: new Date("sept 2018"),
    endDate: new Date("sept 2020"),
    category: "school",
    technologies: [],
  },
]
