/* eslint-disable max-lines */

import { TimeLineItemType } from "@/lib/types/Timeline"

export const timelineElements: TimeLineItemType[] = [
  {
    title: "Fullstack Developer",
    description: "Subscription-based fitness social platform",
    company: "OnlyFits",
    startDate: new Date("jul 2025"),
    endDate: new Date("aug 2025"),
    category: "project",
    technologies: [
      "NextJs",
      "Better Auth",
      "TypeScript",
      "Stripe",
      "Tailwind",
      "MongoDB",
    ],
    tasks: [
      "User authentication & role management",
      "Content creation & subscription system",
      "Real-time chat & social features",
      "Stripe payment integration",
      "Multi-language support (FR/EN)",
      "Responsive UI with shadcn/ui",
      "MongoDB database design",
      "API development & state management",
    ],
    siteUrl: "",
    image: "",
  },
  {
    title: "Apprenticeship as a Fullstack Developer",
    startDate: new Date("oct 2021"),
    endDate: new Date("30 sept 2024"),
    description: "Internal procedures automation",
    tasks: [
      "Requirements gathering and analysis to understand the business needs\n\r",
      "Identify key possible missions \n\r",
      "Create, build and maintain 11 internal applications to automate processes and improve operational efficiency\n\r",
      "Organized and led presentation meetings \n\r",
      "Agile development methodology",
    ],
    company: "HORIBA France",
    category: "work",
    technologies: [
      "NextJs",
      "Power Apps",
      "Power Automate",
      "SharePoint",
      "AgilePoint",
    ],
  },
  {
    title: "Masters's Degree in Computer Science",
    startDate: new Date("sept 2022"),
    endDate: new Date("sept 2024"),
    description:
      "Obtained my Master's degree in computer science, where I learned the basics of programming.",
    company: "Sup De Vinci",
    category: "school",
    technologies: ["JavaScript"],
  },
  {
    title: "Lead Developer",
    description:
      "Web application aimed at the professional retraining of military personnel",
    company: "Implic-Action",
    tasks: [
      "Manage a 7-man team, project planning",
      "Project architecture (structure, package selection, ESLint configuration, etc.)",
      "Break down complex epics into smaller, manageable tasks",
      "Full-stack development",
    ],
    startDate: new Date("aug 2024"),
    endDate: new Date("may 2024"),
    category: "project",
    technologies: [
      "NextJs",
      "Prisma",
      "Linear",
      "Github Actions",
      "Docker",
      "Tailwind",
      "Tanstack Query",
      "TypeScript",
    ],
    image: "",
  },
  {
    title: "Fullstack Developer",
    description: "Tournament Management System Backend",
    company: "OnlyFits",
    startDate: new Date("jul 2025"),
    endDate: new Date("aug 2025"),
    category: "project",
    technologies: ["Go", "Cobra", "GORM", "SQLite", "JWT", "Viper"],
    tasks: [
      "Designed and implemented tournament management system architecture",
      "Created CLI interface using Cobra framework for tournament operations",
      "Implemented public and protected routes for API endpoints",
      "Used Viper for configuration management",
      "Implemented user authentication with JWT tokens and password hashing",
      "Developed CRUD operations for tournaments, teams, and matches",
      "Created interactive command-line prompts for user input",
      "Set up SQLite database with GORM ORM",
      "Implemented match scoring and winner determination logic",
    ],
    gitUrl: "https://github.com/matheusnb99/sdv-m2-renf-backend-go-cobra",
    image: "",
  },

  {
    title: "Fullstack Developer",
    description: "Azure Cloud VM Management Platform",
    company: "",
    startDate: new Date("jul 2023"),
    endDate: new Date("jul 2023"),
    category: "project",
    technologies: [
      "NextJs",
      "TypeScript",
      "Tailwind",
      "Prisma",
      "Azure",
      "Tanstack Query",
    ],
    tasks: [
      "Built cloud VM management platform using Azure",
      "Implemented 3-tier user authentication system",
      "Created automated VM lifecycle management",
      "Built RESTful API for Azure resources",
      "Added real-time VM monitoring",
      "Designed resource creation wizard",
      "Integrated Azure ARM APIs",
      "Implemented cost management",
      "Built responsive Tailwind UI",
    ],
    gitUrl: "",
    image: "",
  },

  {
    title: "Fullstack Developer",
    description: "Japanese products e-commerce website",
    company: "Momotaro",
    startDate: new Date("jul 2023"),
    endDate: new Date("dec 2023"),
    category: "project",
    technologies: ["NextJs", "Next Auth", "TypeScript", "Express", "Tailwind"],
    siteUrl: "",
    image: "",
  },
  {
    title: "Bachelor's Degree in Computer Science",
    startDate: new Date("sept 2021"),
    endDate: new Date("sept 2022"),
    description:
      "Obtained my Bachelor's degree in computer science, where I learned the basics of programming.",
    company: "Sup De Vinci",
    category: "school",
    technologies: [
      "JavaScript",
      "TypeScript",
      "React",
      "NextJs",
      "Spring Boot",
    ],
  },
  {
    title: "DUT Informatique (Two-year technical degree in computer science)",
    description:
      "First year of my DUT in computer science, where I learned the basics of programming.",
    company: "Paris Saclay University",
    startDate: new Date("sept 2018"),
    endDate: new Date("sept 2020"),
    category: "school",
    technologies: [],
  },
]
