import BetterAuthIcon from "@/lib/images/svg/BetterAuthIcon"
import JWTIcon from "@/lib/images/svg/JWTIcon"
import NextAuthIcon from "@/lib/images/svg/NextAuthIcon"
import ViperIcon from "@/lib/images/svg/ViperIcon"
import { BiLogoGoLang } from "react-icons/bi"
import { FaJava } from "react-icons/fa"
import { GiCobra } from "react-icons/gi"
import {
  SiCss3,
  SiDjango,
  SiDocker,
  SiExpress,
  SiGithub,
  SiGithubactions,
  SiHtml5,
  SiJavascript,
  SiLinear,
  SiMicrosoftsharepoint,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNotion,
  SiPhp,
  SiPowerapps,
  SiPowerautomate,
  SiPrisma,
  SiReact,
  SiReactquery,
  SiRedis,
  SiSpringboot,
  SiSqlite,
  SiStripe,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si"
import { VscAzure } from "react-icons/vsc"

export const TECH_STACK_ICONS = {
  "JavaScript": <SiJavascript className="w-6 h-6" />,
  "TypeScript": <SiTypescript className="w-6 h-6" />,
  "React": <SiReact className="w-6 h-6" />,
  "NextJs": <SiNextdotjs className="w-6 h-6" />,
  "php": <SiPhp className="w-6 h-6" />,
  "docker": <SiDocker className="w-6 h-6" />,
  "Django": <SiDjango className="w-6 h-6" />,
  "MySql": <SiMysql className="w-6 h-6" />,
  "MongoDB": <SiMongodb className="w-6 h-6" />,
  "Redis": <SiRedis className="w-6 h-6" />,
  "Tailwind": <SiTailwindcss className="w-6 h-6" />,
  "HTML": <SiHtml5 className="w-6 h-6" />,
  "CSS": <SiCss3 className="w-6 h-6" />,
  "Java": <FaJava className="w-6 h-6" />,
  "Spring Boot": <SiSpringboot className="w-6 h-6" />,
  "Prisma": <SiPrisma className="w-6 h-6" />,
  "Notion": <SiNotion className="w-6 h-6" />,
  "Github": <SiGithub className="w-6 h-6" />,
  "Github Actions": <SiGithubactions className="w-6 h-6" />,
  "Express": <SiExpress className="w-6 h-6" />,
  "Next Auth": <NextAuthIcon />,
  "Docker": <SiDocker className="w-6 h-6" />,
  "Tanstack Query": <SiReactquery className="w-6 h-6" />,
  "Linear": <SiLinear className="w-6 h-6" />,
  "Power Apps": <SiPowerapps className="w-6 h-6" />,
  "Power Automate": <SiPowerautomate className="w-6 h-6" />,
  "SharePoint": <SiMicrosoftsharepoint className="w-6 h-6" />,
  "AgilePoint": null,
  "Stripe": <SiStripe className="w-6 h-6" />,
  "Azure": <VscAzure className="w-6 h-6" />,
  "Go": <BiLogoGoLang className="w-6 h-6" />,
  "Cobra": <GiCobra className="w-6 h-6" />,
  "SQLite": <SiSqlite className="w-6 h-6" />,
  "Better Auth": <BetterAuthIcon />,
  "Viper": <ViperIcon />,
  "GORM": null,
  "JWT": <JWTIcon />,
}

export const TECH_STACK_LINKS = {
  "JavaScript": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  "TypeScript": "https://www.typescriptlang.org/",
  "React": "https://react.dev/",
  "NextJs": "https://nextjs.org/",
  "php": "https://www.php.net/",
  "docker": "https://www.docker.com/",
  "Django": "https://www.djangoproject.com/",
  "MySql": "https://www.mysql.com/",
  "MongoDB": "https://www.mongodb.com/",
  "Redis": "https://redis.io/",
  "Tailwind": "https://tailwindcss.com/",
  "HTML": "https://developer.mozilla.org/en-US/docs/Web/HTML",
  "CSS": "https://developer.mozilla.org/en-US/docs/Web/CSS",
  "Java": "https://www.java.com/",
  "Spring Boot": "https://spring.io/projects/spring-boot",
  "Prisma": "https://www.prisma.io/",
  "Notion": "https://www.notion.so/",
  "Github": "https://github.com/",
  "Github Actions": "https://github.com/features/actions",
  "Express": "https://expressjs.com/",
  "Next Auth": "https://next-auth.js.org/",
  "Docker": "https://www.docker.com/",
  "Tanstack Query": "https://tanstack.com/query/latest",
  "Linear": "https://linear.app/",
  "Power Apps": "https://powerapps.microsoft.com/",
  "Power Automate": "https://powerautomate.microsoft.com/",
  "SharePoint":
    "https://www.microsoft.com/en-us/microsoft-365/sharepoint/collaboration",
  "AgilePoint": "https://www.agilepoint.com/",
  "Stripe": "https://stripe.com/",
  "Azure": "https://azure.microsoft.com/",
  "Go": "https://go.dev/",
  "Cobra": "https://github.com/spf13/cobra",
  "SQLite": "https://www.sqlite.org/",
  "Better Auth": "https://www.better-auth.com/",
  "Viper": "https://github.com/spf13/viper",
  "GORM": "https://gorm.io/",
  "JWT": "https://jwt.io/",
}
