import BetterAuthIcon from "@/lib/images/svg/BetterAuthIcon"
import JWTIcon from "@/lib/images/svg/JWTIcon"
import NextAuthIcon from "@/lib/images/svg/NextAuthIcon"
import ViperIcon from "@/lib/images/svg/ViperIcon"
import { StackOptions } from "@/lib/types/Timeline"
import { ReactNode } from "react"
import { BiLogoGoLang } from "react-icons/bi"
import { FaJava } from "react-icons/fa"
import { GiCobra } from "react-icons/gi"
import { MdOutlineDisabledByDefault } from "react-icons/md"
import {
  SiAstro,
  SiCss3,
  SiDjango,
  SiDocker,
  SiExpress,
  SiGithub,
  SiGithubactions,
  SiHtml5,
  SiJavascript,
  SiLinear,
  SiMicrosoftsharepoint,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNginx,
  SiNotion,
  SiOpnsense,
  SiPhp,
  SiPostgresql,
  SiPowerapps,
  SiPowerautomate,
  SiPrisma,
  SiProxmox,
  SiReact,
  SiReactquery,
  SiRedis,
  SiSpringboot,
  SiSqlite,
  SiStripe,
  SiTailwindcss,
  SiTypescript,
  SiWindows,
} from "react-icons/si"
import { VscAzure } from "react-icons/vsc"

export const TECH_STACK_ICONS: Record<StackOptions, ReactNode | null> = {
  "JavaScript": <SiJavascript className="w-6 h-6" />,
  "TypeScript": <SiTypescript className="w-6 h-6" />,
  "React": <SiReact className="w-6 h-6" />,
  "NextJs": <SiNextdotjs className="w-6 h-6" />,
  "php": <SiPhp className="w-6 h-6" />,
  "Django": <SiDjango className="w-6 h-6" />,
  "MySql": <SiMysql className="w-6 h-6" />,
  "MongoDB": <SiMongodb className="w-6 h-6" />,
  "Redis": <SiRedis className="w-6 h-6" />,
  "Tailwind": <SiTailwindcss className="w-6 h-6" />,
  "HTML": <SiHtml5 className="w-6 h-6" />,
  "CSS": <SiCss3 className="w-6 h-6" />,
  "Java": <FaJava className="w-6 h-6" />,
  "Spring Boot": <SiSpringboot className="w-6 h-6" />,
  "Prisma": <SiPrisma className="w-6 h-6" />,
  "Notion": <SiNotion className="w-6 h-6" />,
  "Github": <SiGithub className="w-6 h-6" />,
  "Github Actions": <SiGithubactions className="w-6 h-6" />,
  "Express": <SiExpress className="w-6 h-6" />,
  "Next Auth": <NextAuthIcon />,
  "Docker": <SiDocker className="w-6 h-6" />,
  "Tanstack Query": <SiReactquery className="w-6 h-6" />,
  "Linear": <SiLinear className="w-6 h-6" />,
  "Power Apps": <SiPowerapps className="w-6 h-6" />,
  "Power Automate": <SiPowerautomate className="w-6 h-6" />,
  "SharePoint": <SiMicrosoftsharepoint className="w-6 h-6" />,
  "Stripe": <SiStripe className="w-6 h-6" />,
  "Azure": <VscAzure className="w-6 h-6" />,
  "Go": <BiLogoGoLang className="w-6 h-6" />,
  "Cobra": <GiCobra className="w-6 h-6" />,
  "SQLite": <SiSqlite className="w-6 h-6" />,
  "Better Auth": <BetterAuthIcon />,
  "Viper": <ViperIcon />,
  "JWT": <JWTIcon />,
  "Proxmox": <SiProxmox className="w-6 h-6" />,
  "OPNsense": <SiOpnsense className="w-6 h-6" />,
  "Nginx": <SiNginx className="w-6 h-6" />,
  "Active Directory": <SiWindows className="w-6 h-6" />,
  "Astro": <SiAstro className="w-6 h-6" />,
  "PostgreSQL": <SiPostgresql className="w-6 h-6" />,
  "AgilePoint": <MdOutlineDisabledByDefault className="w-6 h-6" color="gray" />,
  "GORM": <MdOutlineDisabledByDefault className="w-6 h-6" color="gray" />,
  "Keepalived": <MdOutlineDisabledByDefault className="w-6 h-6" color="gray" />,
  "Bind9": <MdOutlineDisabledByDefault className="w-6 h-6" color="gray" />,
  "Zabbix": <MdOutlineDisabledByDefault className="w-6 h-6" color="gray" />,
}

export const TECH_STACK_LINKS: Record<StackOptions, string> = {
  "JavaScript": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  "TypeScript": "https://www.typescriptlang.org/",
  "React": "https://react.dev/",
  "NextJs": "https://nextjs.org/",
  "php": "https://www.php.net/",
  "Django": "https://www.djangoproject.com/",
  "MySql": "https://www.mysql.com/",
  "MongoDB": "https://www.mongodb.com/",
  "Redis": "https://redis.io/",
  "Tailwind": "https://tailwindcss.com/",
  "HTML": "https://developer.mozilla.org/en-US/docs/Web/HTML",
  "CSS": "https://developer.mozilla.org/en-US/docs/Web/CSS",
  "Java": "https://www.java.com/",
  "Spring Boot": "https://spring.io/projects/spring-boot",
  "Prisma": "https://www.prisma.io/",
  "Notion": "https://www.notion.so/",
  "Github": "https://github.com/",
  "Github Actions": "https://github.com/features/actions",
  "Express": "https://expressjs.com/",
  "Next Auth": "https://next-auth.js.org/",
  "Docker": "https://www.docker.com/",
  "Tanstack Query": "https://tanstack.com/query/latest",
  "Linear": "https://linear.app/",
  "Power Apps": "https://powerapps.microsoft.com/",
  "Power Automate": "https://powerautomate.microsoft.com/",
  "SharePoint":
    "https://www.microsoft.com/en-us/microsoft-365/sharepoint/collaboration",
  "AgilePoint": "https://www.agilepoint.com/",
  "Stripe": "https://stripe.com/",
  "Azure": "https://azure.microsoft.com/",
  "Go": "https://go.dev/",
  "Cobra": "https://github.com/spf13/cobra",
  "SQLite": "https://www.sqlite.org/",
  "Better Auth": "https://www.better-auth.com/",
  "Viper": "https://github.com/spf13/viper",
  "GORM": "https://gorm.io/",
  "JWT": "https://jwt.io/",
  "Proxmox": "https://proxmox.com/en/",
  "OPNsense": "https://opnsense.org/",
  "Nginx": "https://nginx.org/",
  "Keepalived":
    "https://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive",
  "Bind9": "https://doc.ubuntu-fr.org/bind9",
  "Active Directory":
    "https://learn.microsoft.com/fr-fr/training/modules/introduction-to-ad-ds/",
  "Zabbix": "https://www.zabbix.com/fr",
  "Astro": "https://astro.build/",
  "PostgreSQL": "https://www.postgresql.org/",
}
