import { BiLogoGoLang } from "react-icons/bi"
import { FaJava } from "react-icons/fa"
import { GiCobra } from "react-icons/gi"
import {
  SiCss3,
  SiDjango,
  SiDocker,
  SiExpress,
  SiGithub,
  SiGithubactions,
  SiHtml5,
  SiJavascript,
  SiLinear,
  SiMicrosoftsharepoint,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNotion,
  SiPhp,
  SiPowerapps,
  SiPowerautomate,
  SiPrisma,
  SiReact,
  SiReactquery,
  SiRedis,
  SiSpringboot,
  SiSqlite,
  SiStripe,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si"
import { VscAzure } from "react-icons/vsc"

export const TECH_STACK_ICONS = {
  "JavaScript": <SiJavascript className="w-6 h-6" />,
  "TypeScript": <SiTypescript className="w-6 h-6" />,
  "React": <SiReact className="w-6 h-6" />,
  "NextJs": <SiNextdotjs className="w-6 h-6" />,
  "php": <SiPhp className="w-6 h-6" />,
  "docker": <SiDocker className="w-6 h-6" />,
  "Django": <SiDjango className="w-6 h-6" />,
  "MySql": <SiMysql className="w-6 h-6" />,
  "MongoDB": <SiMongodb className="w-6 h-6" />,
  "Redis": <SiRedis className="w-6 h-6" />,
  "Tailwind": <SiTailwindcss className="w-6 h-6" />,
  "HTML": <SiHtml5 className="w-6 h-6" />,
  "CSS": <SiCss3 className="w-6 h-6" />,
  "Java": <FaJava className="w-6 h-6" />,
  "Spring Boot": <SiSpringboot className="w-6 h-6" />,
  "Prisma": <SiPrisma className="w-6 h-6" />,
  "Notion": <SiNotion className="w-6 h-6" />,
  "Github": <SiGithub className="w-6 h-6" />,
  "Github Actions": <SiGithubactions className="w-6 h-6" />,
  "Express": <SiExpress className="w-6 h-6" />,
  "Next Auth": null,
  "Docker": <SiDocker className="w-6 h-6" />,
  "Tanstack Query": <SiReactquery className="w-6 h-6" />,
  "Linear": <SiLinear className="w-6 h-6" />,
  "Power Apps": <SiPowerapps className="w-6 h-6" />,
  "Power Automate": <SiPowerautomate className="w-6 h-6" />,
  "SharePoint": <SiMicrosoftsharepoint className="w-6 h-6" />,
  "AgilePoint": null,
  "Stripe": <SiStripe className="w-6 h-6" />,
  "Azure": <VscAzure className="w-6 h-6" />,
  "Go": <BiLogoGoLang className="w-6 h-6" />,
  "Cobra": <GiCobra className="w-6 h-6" />,
  "SQLite": <SiSqlite className="w-6 h-6" />,
}
